### PR TITLE
Investigate strict errors

### PR DESCRIPTION
**Pull request by lucanos**

### CODE REVIEW

**Comment by lucanos** [comment]
Cancelling

**Comment by lifeinthegrid** [comment]
Hey Luke,

 

Thanks for checking these in.  I’ll try and get them merged sometime in February…

 

Cheers~

**Comment by lifeinthegrid** [comment]
Hey Luke,

 

I was going to try and integrate your changes into the main line, but when I do a split diff, I can’t really see what changed because the whole file is showing as changed…   I think it may be easier to just add you as a contributor to the main line and merge in your changes again.   It looks like you know what you’re doing and then way we won’t have to worry about merging branches…

 

If you want to send me your github email I’ll add you as a main line contributor, if that’s ok with you…

**Comment by lucanos** [comment]
Hey Cory,

My GitHub email is lucanos@gmail.com

The whole file diff is probably due to my editor adjusting indents, etc. (I
will try and maintain the coding standards already in the repo for any
future changes.)

Cheers,
Luke

**Comment by lifeinthegrid** [comment]
Hi Luke,

 

You should be added now, let me know if you run into any issues submitting your changes…   As long as they are small bug fixes or improvements feel free to just add them to the master branch…

 

 

Cheers~

**Pull request closed without merging**
